/**
 * One-time migration: sanitize (EXIF-strip) existing raw photo originals.
 *
 * Run: npx tsx scripts/migrate-sanitize-existing-photos.ts
 *
 * For each diary catch photo that has an originalUrl:
 *   - Local file  → sanitize in-place with Sharp (GPS/EXIF stripped)
 *   - Firebase URL → clear originalUrl from DB (variants remain, they are already EXIF-stripped)
 *
 * Safe to re-run: already-sanitized files are re-processed (idempotent for EXIF strip).
 */

import path from 'path';
import fs from 'fs';
import { promises as fsPromises } from 'fs';
import sharp from 'sharp';
import { db } from '../server/db';
import { diaryCatches } from '../shared/schema';
import { sql } from 'drizzle-orm';

interface PhotoObject {
  id?: string;
  url?: string;
  originalUrl?: string;
  status?: string;
  variants?: unknown[];
  placeholder?: string;
  [key: string]: unknown;
}

async function sanitizeInPlace(filePath: string): Promise<void> {
  const tmpPath = `${filePath}.sanitizing.tmp`;
  try {
    await sharp(filePath)
      .rotate()
      .withMetadata(false)
      .jpeg({ quality: 95, mozjpeg: true })
      .toFile(tmpPath);
    await fsPromises.rename(tmpPath, filePath);
  } catch (err) {
    try { await fsPromises.unlink(tmpPath); } catch {}
    throw err;
  }
}

async function run() {
  console.log('[MIGRATE] Starting photo sanitization migration...\n');

  const allCatches = await db
    .select()
    .from(diaryCatches)
    .where(sql`photos IS NOT NULL AND jsonb_array_length(photos) > 0`);

  console.log(`[MIGRATE] Found ${allCatches.length} catches with photos\n`);

  let sanitizedLocal = 0;
  let clearedFirebase = 0;
  let skipped = 0;
  let errors = 0;

  for (const catch_ of allCatches) {
    if (!catch_.photos || !Array.isArray(catch_.photos)) continue;

    const photos = catch_.photos as PhotoObject[];
    let needsUpdate = false;

    const updatedPhotos = await Promise.all(photos.map(async (photo) => {
      if (typeof photo !== 'object' || !photo.originalUrl) return photo;

      const originalUrl = photo.originalUrl as string;

      if (originalUrl.startsWith('/attached_assets/') || originalUrl.startsWith('/uploads/')) {
        // Local file — sanitize in-place
        const localPath = path.join(process.cwd(), originalUrl.slice(1));

        if (!fs.existsSync(localPath)) {
          console.warn(`[MIGRATE] Local file not found, skipping: ${localPath}`);
          skipped++;
          return photo;
        }

        try {
          await sanitizeInPlace(localPath);
          console.log(`[MIGRATE] Sanitized local file: ${path.basename(localPath)} (photo ${photo.id ?? 'unknown'})`);
          sanitizedLocal++;
          needsUpdate = true;
          return { ...photo, _exifSanitized: true };
        } catch (err) {
          console.error(`[MIGRATE] Failed to sanitize ${localPath}:`, err);
          errors++;
          return photo;
        }

      } else if (originalUrl.startsWith('https://')) {
        // Firebase URL — cannot re-process without downloading; clear from DB.
        // Variants (WebP/JPEG) were generated by ImageService and are already EXIF-stripped.
        console.log(`[MIGRATE] Clearing Firebase originalUrl for photo ${photo.id ?? 'unknown'}`);
        clearedFirebase++;
        needsUpdate = true;
        const { originalUrl: _removed, ...rest } = photo;
        return { ...rest, _firebaseOriginalCleared: true };

      } else {
        console.warn(`[MIGRATE] Unknown URL scheme, skipping: ${originalUrl}`);
        skipped++;
        return photo;
      }
    }));

    if (needsUpdate) {
      await db
        .update(diaryCatches)
        .set({
          photos: sql`${JSON.stringify(updatedPhotos)}::jsonb`,
          updatedAt: new Date()
        })
        .where(sql`id = ${catch_.id}`);
    }
  }

  console.log('\n[MIGRATE] ─────────────────────────────────────────');
  console.log(`[MIGRATE] Done.`);
  console.log(`[MIGRATE]   Sanitized local files : ${sanitizedLocal}`);
  console.log(`[MIGRATE]   Firebase URLs cleared : ${clearedFirebase}`);
  console.log(`[MIGRATE]   Skipped (file missing): ${skipped}`);
  console.log(`[MIGRATE]   Errors               : ${errors}`);
  console.log('[MIGRATE] ─────────────────────────────────────────');

  if (errors > 0) {
    process.exit(1);
  }
}

run().catch((err) => {
  console.error('[MIGRATE] Fatal error:', err);
  process.exit(1);
});
